### ISSUE TITLE
Class 'Solitweb\DirectAdmin\DirectAdmin' not found

### ISSUE THREAD

**Issue by ARNHOE** [solitweb/laravel-directadmin#4]
![schermafbeelding 2017-06-05 om 15 39 09](https://cloud.githubusercontent.com/assets/1517053/26785941/1419225a-4a05-11e7-8ad1-4e264a1253de.png)

**Comment by ARNHOE** [comment]
@stijnvanouplines This is because the following dependency (https://github.com/solitweb/directadmin) has its 'src' folder named as 'scr'. This is fixed in master but in 3.0.1 it is not.

So either we need to update composer.json to dev-master or you should make a new release 3.0.2 based on master to fix the above issue.

**Comment by stijnvanouplines** [comment]
Hi @ARNHOE Can you please check? I fixed the issue!

**Comment by ARNHOE** [comment]
All good now, cheers @stijnvanouplines 👍

**Comment by stijnvanouplines** [comment]
@ARNHOE My pleasure!
